import { chromium } from 'playwright-core';
const CHROME = 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const browser = await chromium.launch({ executablePath: CHROME, headless: true });
const page = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await page.goto('http://localhost:5199', { waitUntil: 'domcontentloaded' });
await page.waitForFunction(`document.getElementById('hero')?.classList.contains('is-live')`, null, { timeout: 60000 });
await page.waitForTimeout(2000);
const hash = `(() => { const c = document.getElementById('hero-canvas'); const d = c.getContext('2d').getImageData(0, Math.floor(c.height/2), 600, 2).data; let h=0; for (let i=0;i<d.length;i+=16) h=(h*31+d[i])>>>0; return h; })()`;
const info = `({frame: window.__heroFrame ? window.__heroFrame() : 'n/a', w: document.getElementById('hero-canvas').width, h: document.getElementById('hero-canvas').height})`;
console.log('t0', await page.evaluate(info), await page.evaluate(hash));
await page.evaluate(`window.__lenis.scrollTo(1500, {immediate:true})`);
await page.waitForTimeout(1600);
console.log('at1500', await page.evaluate(info), await page.evaluate(hash));
await page.evaluate(`window.__lenis.scrollTo(0, {immediate:true})`);
await page.waitForTimeout(1600);
console.log('back0', await page.evaluate(info), await page.evaluate(hash));
await page.waitForTimeout(1500);
console.log('back0+1.5s', await page.evaluate(info), await page.evaluate(hash));
await browser.close();
